### ISSUE TITLE
Two way Ref causes compile error

### ISSUE THREAD

**Issue by FSM1** [szokodiakos/typegoose#211]
model classes both Ref each other: eg.

```
// User.ts
import { Pet } from './Pet';

export class User extends Typegoose {
    @IsEmail()
    @prop({required: true, unique: true, sparse: true })
    public email: string;

    @prop({required: true})
    public password: string;

    // more code here

    //source of problems
    @arrayProp({ itemsRef: Pet, default: [], required: false })
    public pets?: Array<Ref<Pet>>;

}

// Pet.ts

import { User } from './User';

export class Pet extends Typegoose {
    @prop({required: true})
    public name: string;

    @prop({ref: User, required: true})
    public owner: Ref<User>;
}

```
the app fails to start and throws the following stack trace:

```

C:\Users\myank\Code\LinumLabs\molecule-sandbox\ApiServer\node_modules\typegoose\lib\prop.js:67
    const instance = new Type();
                     ^
TypeError: Type is not a constructor
    at baseProp (\node_modules\typegoose\lib\prop.js:67:22)
    at \node_modules\typegoose\lib\prop.js:105:5
    at DecorateProperty (\node_modules\reflect-metadata\Reflect.ts:1214:35)
    at Object.decorate (\node_modules\reflect-metadata\Reflect.ts:737:24)
    at Object.__decorate (\node_modules\tslib\tslib.js:89:96)
    at Object.<anonymous> (\models\User.ts:32:5)
    at Module._compile (module.js:653:30)
    at Module.m._compile (\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions.js (module.js:664:10)
    at Object.require.extensions.(anonymous function) [as .ts] (\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (models\Pet.ts:3:1)

```

If I remove the User.pets arrayProp then the app compiles again.

**Comment by FSM1** [comment]
this seems to happen whenever there are cyclic dependencies in the models, as evidenced by #116, #143

**Comment by murbanowicz** [comment]
any news on that?
I get rid of this issue after using ref with string name on both sides of the relationship and it is working fine now, but it's not as it should be.
@szokodiakos any idea?

**Comment by hasezoey** [comment]
i would help, but i would need to know these things first:
- is this still a problem with typegoose 5.8.1+
- and how its called (to exclude the type error / a misunderstanding)

**Comment by hasezoey** [comment]
this should be fixed with v6.0.0

@Ben305 this can be closed

**Comment by sverraest** [comment]
I'm still getting this in 6.1.2.
Creating a bidirectional Ref between two documents is throwing:

{ MongooseError: Invalid ref at path "registration". Got undefined }
(this is when I have an Invitation.registration and Registration.invitation one to one bidirectional setup).

**Comment by hasezoey** [comment]
@sverraest when you have issues, please open a new issue, on the new repo

**Comment by tzvc** [comment]
Hey there, I'm still getting the error with `7.3.2` any updates on this ?

```
Error: Option "ref" for "Workspace.demo_application" was defined with an arrow-function, but the function returned null/undefined!
```

**Comment by hasezoey** [comment]
@theochampion no support here anymore, please open an new issue at the new repo

PS: this is an different error
